### ISSUE TITLE
extras does not conform to PEP 396

### ISSUE THREAD

**Issue by ddriddle** [testing-cabal/extras#5]
For our package management we use automated tooling to extract version numbers from python packages. I would like to request that you change the `__version__` attribute so that it conforms to PEP 396. Currently `__version__` returns a tuple according to PEP 396 it should return a string.

[PEP 396](https://www.python.org/dev/peps/pep-0396/) states:

* When a module (or package) includes a version number, the version SHOULD be available in the `__version__` attribute.
* The `__version__` attribute's value SHOULD be a string.

**Comment by ddriddle** [comment]
Created pull request #6 to fix this issue.

**Comment by rbtcollins** [comment]
Much better to use the distribution metadata pip maintains, since unlike in-package data it can't suffer skew.
